program Lotus;

uses
  Forms,
  DB,
  DBTables,
  UMenuP in 'UMenuP.pas' {fMenuP},
  UGrupos in 'UGrupos.pas' {fGrupos},
  USubGrupos in 'USubGrupos.pas' {fSubGrupos},
  UFornecedores in 'UFornecedores.pas' {fFornecedores},
  UMaterial in 'UMaterial.pas' {fMaterial},
  UGrade in 'UGrade.pas' {fGrade},
  UOrdemCompra in 'UOrdemCompra.pas' {fOrdemCompra},
  UOrdemCompraCor in 'UOrdemCompraCor.pas' {fOrdemCompraCor},
  UEmpresa in 'UEmpresa.pas' {fEmpresa},
  URelOrdemCompra in 'URelOrdemCompra.pas' {fRelOrdemCompra},
  UProduto in 'UProduto.pas' {fProduto},
  UProdutoGrade in 'UProdutoGrade.pas' {fProdutoGrade},
  URelMaterial in 'URelMaterial.pas' {fRelMaterial},
  UPrevMaterial in 'UPrevMaterial.pas' {fPrevMaterial},
  UVendedor in 'UVendedor.pas' {fVendedor},
  UPedido in 'UPedido.pas' {fPedido},
  UCliente in 'UCliente.pas' {fCliente},
  UPedidoGrade in 'UPedidoGrade.pas' {fPedidoGrade},
  UPedidoMat in 'UPedidoMat.pas' {fPedidoMat},
  UPedidoDesconto in 'UPedidoDesconto.pas' {fPedidoDesconto},
  URelPedido in 'URelPedido.pas' {fRelPedido},
  UPrevRelClientes in 'UPrevRelClientes.pas' {fPrevRelClientes},
  URelClientes in 'URelClientes.pas' {fRelClientes},
  UPrevFornecedores in 'UPrevFornecedores.pas' {fPrevFornecedores},
  URelFornecedores in 'URelFornecedores.pas' {fRelFornecedores},
  UPrevVendedores in 'UPrevVendedores.pas' {fPrevVendedores},
  URelVendedores in 'URelVendedores.pas' {fRelVendedores},
  ULote in 'ULote.pas' {fLote},
  USetor in 'USetor.pas' {fSetor},
  UTipoCobranca in 'UTipoCobranca.pas' {fTipoCobranca},
  UCopiaPedidos in 'UCopiaPedidos.pas' {fCopiaPedidos},
  UEmissaoNotaFiscal in 'UEmissaoNotaFiscal.pas' {fEmissaoNotaFiscal},
  UContas in 'UContas.pas' {fContas},
  UPlanoContas in 'UPlanoContas.pas' {fPlanoContas},
  UMovimentos in 'UMovimentos.pas' {fMovimentos},
  UEntradaMovimentos in 'UEntradaMovimentos.pas' {fEntradaMovimentos},
  UPrevContas in 'UPrevContas.pas' {fPrevContas},
  URelContas in 'URelContas.pas' {fRelContas},
  UContasPagar in 'UContasPagar.pas' {fContasPagar},
  ULancaCPagar in 'ULancaCPagar.pas' {fLancaCPagar},
  ULancaCReceber in 'ULancaCReceber.pas' {fLancaCReceber},
  UContasPagarPag in 'UContasPagarPag.pas' {fContasPagarPag},
  UContasReceberPag in 'UContasReceberPag.pas' {fContasReceberPag},
  URelCReceber in 'URelCReceber.pas' {fRelCReceber},
  UBuscaPedido in 'UBuscaPedido.pas' {fBuscaPedido},
  UConsNotaFiscal in 'UConsNotaFiscal.pas' {fConsNotaFiscal},
  UNotaEntrada in 'UNotaEntrada.pas' {fNotaEntrada},
  UConsNotaEnt in 'UConsNotaEnt.pas' {fConsNotaEnt},
  URelNotaEntrada in 'URelNotaEntrada.pas' {fRelNotaEntrada},
  USobre in 'USobre.pas' {fSobre},
  UConsLote in 'UConsLote.pas' {fConsLote},
  URelPagForn in 'URelPagForn.pas' {fRelPagForn},
  URelPgtoJuros in 'URelPgtoJuros.pas' {fRelPgtoJuros},
  URelRecCli in 'URelRecCli.pas' {fRelRecCli},
  UPrevRecCli in 'UPrevRecCli.pas' {fPrevRecCli},
  UPrevPgtoJuros in 'UPrevPgtoJuros.pas' {fPrevPgtoJuros},
  UPrevDuplicatas in 'UPrevDuplicatas.pas' {fPrevDuplicatas},
  UPrevPagForn in 'UPrevPagForn.pas' {fPrevPagForn},
  UAlteraJuros in 'UAlteraJuros.pas' {fAlteraJuros},
  UBaixaItOC in 'UBaixaItOC.pas' {fBaixaItOC},
  UBaixaPedido in 'UBaixaPedido.pas' {fBaixaPedido},
  UBuscaOC in 'UBuscaOC.pas' {fBuscaOC},
  UConsCPagarHist in 'UConsCPagarHist.pas' {fConsCPagarHist},
  UConsCReceberHist in 'UConsCReceberHist.pas' {fConsCReceberHist},
  UConsFatDiario in 'UConsFatDiario.pas' {fConsFatDiario},
  UConsNPedCli in 'UConsNPedCli.pas' {fConsNPedCli},
  UConsPedido in 'UConsPedido.pas' {fConsPedido},
  UConsPedidoNota in 'UConsPedidoNota.pas' {fConsPedidoNota},
  UCPagarAltera in 'UCPagarAltera.pas' {fCPagarAltera},
  UCReceberAltera in 'UCReceberAltera.pas' {fCReceberAltera},
  UEntrExtOC in 'UEntrExtOC.pas' {fEntrExtOC},
  UEstPagamento in 'UEstPagamento.pas' {fEstPagamento},
  UEstPagamentoPagar in 'UEstPagamentoPagar.pas' {fEstPagamentoPagar},
  UEtiqCliente in 'UEtiqCliente.pas' {fEtiqCliente},
  UEtiqFornecedor in 'UEtiqFornecedor.pas' {fEtiqFornecedor},
  UEtiqVendedor in 'UEtiqVendedor.pas' {fEtiqVendedor},
  UGeraArquivo in 'UGeraArquivo.pas' {fGeraArquivo},
  UGradeRotulo in 'UGradeRotulo.pas' {fGradeRotulo},
  ULancComissao in 'ULancComissao.pas' {fLancComissao},
  ULancComissaoMod in 'ULancComissaoMod.pas' {fLancComissaoMod},
  ULojas in 'ULojas.pas' {fLojas},
  UModelista in 'UModelista.pas' {fModelista},
  UNotaEntradaGrade in 'UNotaEntradaGrade.pas' {fNotaEntradaGrade},
  UOpcaoPedido in 'UOpcaoPedido.pas' {fOpcaoPedido},
  UParametros in 'UParametros.pas' {fParametros},
  UPedidoCancItem in 'UPedidoCancItem.pas' {fPedidoCancItem},
  UPgtoComissaoMod in 'UPgtoComissaoMod.pas' {fPgtoComissaoMod},
  UPrevExtComissao2 in 'UPrevExtComissao2.pas' {fPrevExtComissao2},
  UPrevExtComissaoMod in 'UPrevExtComissaoMod.pas' {fPrevExtComissaoMod},
  UPrevExtComissaoModPed in 'UPrevExtComissaoModPed.pas' {fPrevExtComissaoModPed},
  UPrevNComprasNatOpe in 'UPrevNComprasNatOpe.pas' {fPrevNComprasNatOpe},
  UPrevNotasNatOpe in 'UPrevNotasNatOpe.pas' {fPrevNotasNatOpe},
  UPrevNotasVendedor in 'UPrevNotasVendedor.pas' {fPrevNotasVendedor},
  UPrevPedidosNaoFat in 'UPrevPedidosNaoFat.pas' {fPrevPedidosNaoFat},
  UPrevRelCPagar in 'UPrevRelCPagar.pas' {fPrevRelCPagar},
  UPrevRelCReceber in 'UPrevRelCReceber.pas' {fPrevRelCReceber},
  UPrevRelRotulos in 'UPrevRelRotulos.pas' {fPrevRelRotulos},
  UPrevVendasVendCli in 'UPrevVendasVendCli.pas' {fPrevVendasVendCli},
  UPrevVendasVendedor in 'UPrevVendasVendedor.pas' {fPrevVendasVendedor},
  UPrevVendasVendRef in 'UPrevVendasVendRef.pas' {fPrevVendasVendRef},
  UQuant in 'UQuant.pas' {fQuant},
  URegioes in 'URegioes.pas' {fRegioes},
  USenha2 in 'USenha2.pas' {fSenha2},
  UUsuarios in 'UUsuarios.pas' {fUsuarios},
  UPermissoes in 'UPermissoes.pas' {fPermissoes},
  ULogin in 'ULogin.pas' {fLogin},
  UAcesso in 'UAcesso.pas' {fAcesso},
  UAtelier in 'UAtelier.pas' {fAtelier},
  UMovTalao in 'UMovTalao.pas' {fMovTalao},
  UEscAtelier in 'UEscAtelier.pas' {fEscAtelier},
  UConsLoteExp in 'UConsLoteExp.pas' {fConsLoteExp},
  ULoteExp in 'ULoteExp.pas' {fLoteExp},
  URequisicao in 'URequisicao.pas' {fRequisicao},
  URequisicaoGrade in 'URequisicaoGrade.pas' {fRequisicaoGrade},
  UConsPedidoLote in 'UConsPedidoLote.pas' {fConsPedidoLote},
  UConsMovTalao in 'UConsMovTalao.pas' {fConsMovTalao},
  UConsMovTalaoD in 'UConsMovTalaoD.pas' {fConsMovTalaoD},
  URelFichaTecnica in 'URelFichaTecnica.pas' {fRelFichaTecnica},
  UPrevCustoSetor in 'UPrevCustoSetor.pas' {fPrevCustoSetor},
  UConsHistMat in 'UConsHistMat.pas' {fConsHistMat},
  UPrevMatMinimo in 'UPrevMatMinimo.pas' {fPrevMatMinimo},
  URelMatMinimo in 'URelMatMinimo.pas' {fRelMatMinimo},
  UConsReq in 'UConsReq.pas' {fConsReq},
  UConsEstoqueMat in 'UConsEstoqueMat.pas' {fConsEstoqueMat},
  ULoteSetor in 'ULoteSetor.pas' {fLoteSetor},
  UConsLoteSetor in 'UConsLoteSetor.pas' {fConsLoteSetor},
  UPrevRelHistMaterial in 'UPrevRelHistMaterial.pas' {fPrevRelHistMaterial},
  UOpcaoTalao in 'UOpcaoTalao.pas' {fOpcaoTalao},
  UPrevMetasProd in 'UPrevMetasProd.pas' {fPrevMetasProd},
  UPrevSitAtelier in 'UPrevSitAtelier.pas' {fPrevSitAtelier},
  URelSitAtelier in 'URelSitAtelier.pas' {fRelSitAtelier},
  UMaoDeObra in 'UMaoDeObra.pas' {fMaoDeObra},
  UConsLoteSetorMI in 'UConsLoteSetorMI.pas' {fConsLoteSetorMI},
  ULoteSetorMI in 'ULoteSetorMI.pas' {fLoteSetorMI},
  UConsMovTalaoMI in 'UConsMovTalaoMI.pas' {fConsMovTalaoMI},
  UNotaFiscalGrade in 'UNotaFiscalGrade.pas' {fNotaFiscalGrade},
  UEscNotaDevol in 'UEscNotaDevol.pas' {fEscNotaDevol},
  UPrevNotaEntrada in 'UPrevNotaEntrada.pas' {fPrevNotaEntrada},
  UConsMovTalaoDMI in 'UConsMovTalaoDMI.pas' {fConsMovTalaoDMI},
  UCopiaFornec in 'UCopiaFornec.pas' {fCopiaFornec},
  UPosicao in 'UPosicao.pas' {fPosicao},
  UPrevCalcMaterialPed in 'UPrevCalcMaterialPed.pas' {fPrevCalcMaterialPed},
  UPrevCalcMaterialLote in 'UPrevCalcMaterialLote.pas' {fPrevCalcMaterialLote},
  UOperAtelier in 'UOperAtelier.pas' {fOperAtelier},
  UPrevPlanejProg in 'UPrevPlanejProg.pas' {fPrevPlanejProg},
  UConsOrdemCompra in 'UConsOrdemCompra.pas' {fConsOrdemCompra},
  UEtiqCx in 'UEtiqCx.pas' {fEtiqCx},
  UPrevPre in 'UPrevPre.pas' {fPrevPre},
  UDctoEst in 'UDctoEst.pas' {fDctoEst},
  UDctoGrade in 'UDctoGrade.pas' {fDctoGrade},
  UConsDcto in 'UConsDcto.pas' {fConsDcto},
  URelRotulos in 'URelRotulos.pas' {fRelRotulos},
  UCopiaDuplicata in 'UCopiaDuplicata.pas' {fCopiaDuplicata},
  URelTalao in 'URelTalao.pas' {fRelTalao},
  UPrevBalancoEst in 'UPrevBalancoEst.pas' {fPrevBalancoEst},
  UContasReceberDev in 'UContasReceberDev.pas' {fContasReceberDev},
  UContasPagarDev in 'UContasPagarDev.pas' {fContasPagarDev},
  UConsLancCPagar in 'UConsLancCPagar.pas' {fConsLancCPagar},
  UConsLancCReceber in 'UConsLancCReceber.pas' {fConsLancCReceber},
  UPedAmostra in 'UPedAmostra.pas' {fPedAmostra},
  UPedAmostraGrade in 'UPedAmostraGrade.pas' {fPedAmostraGrade},
  UPedAmostraMat in 'UPedAmostraMat.pas' {fPedAmostraMat},
  UPrevMetasProdRef in 'UPrevMetasProdRef.pas' {fPrevMetasProdRef},
  UPrevRelOC in 'UPrevRelOC.pas' {fPrevRelOC},
  UPrevTalaoAmostra in 'UPrevTalaoAmostra.pas' {fPrevTalaoAmostra},
  URelTalaoAmostra in 'URelTalaoAmostra.pas' {fRelTalaoAmostra},
  UBaixaPedAmostra in 'UBaixaPedAmostra.pas' {fBaixaPedAmostra},
  URelEtiqCx in 'URelEtiqCx.pas' {fRelEtiqCx},
  URelTalaoMI in 'URelTalaoMI.pas' {fRelTalaoMI},
  URelLote in 'URelLote.pas' {fRelLote},
  URelTalaoExpSeq in 'URelTalaoExpSeq.pas' {fRelTalaoExpSeq},
  URelTesteEst in 'URelTesteEst.pas' {fRelTesteEst},
  UConsComissao in 'UConsComissao.pas' {fConsComissao},
  UPrevCliRef in 'UPrevCliRef.pas' {fPrevCliRef},
  URelCliRef in 'URelCliRef.pas' {fRelCliRef},
  URelacaoGeral in 'URelacaoGeral.pas' {fRelacaoGeral},
  UConsHistCli in 'UConsHistCli.pas' {fConsHistCli},
  UFabrica in 'UFabrica.pas' {fFabrica},
  UPrevRelAcumFab in 'UPrevRelAcumFab.pas' {fPrevRelAcumFab},
  URelAcumFab in 'URelAcumFab.pas' {fRelAcumFab},
  UOS in 'UOS.pas' {fOS},
  UConsOS in 'UConsOS.pas' {fConsOS},
  URelOS in 'URelOS.pas' {fRelOS},
  UConsOCFornec in 'UConsOCFornec.pas' {fConsOCFornec},
  USenha in 'USenha.pas' {fSenha},
  UPrevRelPedEmb in 'UPrevRelPedEmb.pas' {fPrevRelPedEmb},
  URelPedEmb in 'URelPedEmb.pas' {fRelPedemb},
  UPrevProdColecao in 'UPrevProdColecao.pas' {fPrevProdColecao},
  URelProdColecao in 'URelProdColecao.pas' {fRelProdColecao},
  UPrevICMS in 'UPrevICMS.pas' {fPrevICMS},
  URelICMS in 'URelICMS.pas' {fRelICMS},
  UDevolucao in 'UDevolucao.pas' {fDevolucao},
  UDevolucaoBaixa in 'UDevolucaoBaixa.pas' {fDevolucaoBaixa},
  UConsDevolucao in 'UConsDevolucao.pas' {fConsDevolucao},
  UDefeitos in 'UDefeitos.pas' {fDefeitos},
  UPendencias in 'UPendencias.pas' {fPendencias},
  UPrevTransfICMS in 'UPrevTransfICMS.pas' {fPrevTransfICMS},
  URelTransfICMS in 'URelTransfICMS.pas' {fRelTransfICMS},
  URelContLoteExp in 'URelContLoteExp.pas' {fRelContLoteExp},
  UMaterialGrade in 'UMaterialGrade.pas' {fMaterialGrade},
  URelEstoque in 'URelEstoque.pas' {fRelEstoque},
  UConstrucao in 'UConstrucao.pas' {fConstrucao},
  UPrevProjecao in 'UPrevProjecao.pas' {fPrevProjecao},
  URelProjecao in 'URelProjecao.pas' {fRelProjecao},
  URelConstrucao in 'URelConstrucao.pas' {fRelConstrucao},
  UPrevEstIntermediario in 'UPrevEstIntermediario.pas' {fPrevEstIntermediario},
  URelEstIntermediario in 'URelEstIntermediario.pas' {fRelEstIntermediario},
  UPrevPrevisaoOC in 'UPrevPrevisaoOC.pas' {fPrevPrevisaoOC},
  URelPrevisaoOC in 'URelPrevisaoOC.pas' {fRelPrevisaoOC},
  URelOC in 'URelOC.pas' {fRelOC},
  URelOrdemCompraMail in 'URelOrdemCompraMail.pas' {fRelOrdemCompraMail},
  SelfPrintDefs in 'SelfPrintDefs.pas',
  SendMail in 'SendMail.pas',
  SendMailOptions in 'SendMailOptions.pas' {FormSendMailOptions},
  URelNotasVendedor in 'URelNotasVendedor.pas' {fRelNotasVendedor},
  URelExtComissao in 'URelExtComissao.pas' {fRelExtComissao},
  UPrevPrevComissao in 'UPrevPrevComissao.pas' {fPrevPrevComissao},
  URelPrevComissao in 'URelPrevComissao.pas' {fRelPrevComissao},
  UPrevEstIntermediarioMI in 'UPrevEstIntermediarioMI.pas' {fPrevEstIntermediarioMI},
  URelEstIntermediarioMI in 'URelEstIntermediarioMI.pas' {fRelEstIntermediarioMI},
  UPgtoComissao2 in 'UPgtoComissao2.pas' {fPgtoComissao2},
  URelCopiaNF2 in 'URelCopiaNF2.pas' {fRelCopiaNF2},
  URelExtComissaoMod in 'URelExtComissaoMod.pas' {fRelExtComissaoMod},
  URelOSMail in 'URelOSMail.pas' {fRelOSMail},
  UPrevRelComprovante in 'UPrevRelComprovante.pas' {fPrevRelComprovante},
  URelComprovante in 'URelComprovante.pas' {fRelComprovante},
  UPrevFaturamento in 'UPrevFaturamento.pas' {fPrevFaturamento},
  URelFaturamento in 'URelFaturamento.pas' {fRelFaturamento},
  UConsEstoqueOC in 'UConsEstoqueOC.pas' {fConsEstoqueOC},
  URelEtiqVendedor in 'URelEtiqVendedor.pas' {fRelEtiqVendedor},
  USenhaExc in 'USenhaExc.pas' {fSenhaExc},
  UNotaFiscalItensOutros in 'UNotaFiscalItensOutros.pas' {fNotaFiscalItensOutros},
  UTrocaMercado in 'UTrocaMercado.pas' {fTrocaMercado},
  URelCPagar in 'URelCPagar.pas' {fRelCPagar},
  URelCPagar2 in 'URelCPagar2.pas' {fRelCPagar2},
  URelComprovante2 in 'URelComprovante2.pas' {fRelComprovante2},
  UEncComissao in 'UEncComissao.pas' {fEncComissao},
  UCopiarOC in 'UCopiarOC.pas' {fCopiarOC},
  UConstrucaoGrupo in 'UConstrucaoGrupo.pas' {fConstrucaoGrupo},
  URelPrevisaoOCDetalhado in 'URelPrevisaoOCDetalhado.pas' {fRelPrevisaoOCDetalhado},
  URelPrevisaoOC2 in 'URelPrevisaoOC2.pas' {fRelPrevisaoOC2},
  UPrevRelRotulos2 in 'UPrevRelRotulos2.pas' {fPrevRelRotulos2},
  UConsOC in 'UConsOC.pas' {fConsOC},
  URelOC2 in 'URelOC2.pas' {fRelOC2},
  URelRotulos3 in 'URelRotulos3.pas' {fRelRotulos3},
  UContasReceber2 in 'UContasReceber2.pas' {fContasReceber2},
  URelCReceber2 in 'URelCReceber2.pas' {fRelCReceber2},
  UHistGeral in 'UHistGeral.pas' {fHistGeral},
  URelHistGeralVend in 'URelHistGeralVend.pas' {fRelHistGeralVend},
  URelHistGeralCli in 'URelHistGeralCli.pas' {fRelHistGeralCli},
  URelHistGeralCliMes in 'URelHistGeralCliMes.pas' {fRelHistGeralCliMes},
  URelHistGeralCliProd in 'URelHistGeralCliProd.pas' {fRelHistGeralCliProd},
  URelHistGeralCliProdCor in 'URelHistGeralCliProdCor.pas' {fRelHistGeralCliProdCor},
  URelHistGeralCliProdMes in 'URelHistGeralCliProdMes.pas' {fRelHistGeralCliProdMes},
  URelHistGeralCliProdMesRes in 'URelHistGeralCliProdMesRes.pas' {fRelHistGeralCliProdMesRes},
  URelHistGeralProd in 'URelHistGeralProd.pas' {fRelHistGeralProd},
  URelHistGeralProdMes in 'URelHistGeralProdMes.pas' {fRelHistGeralProdMes},
  UConsMovSetor in 'UConsMovSetor.pas' {fConsMovSetor},
  URelMovSetor in 'URelMovSetor.pas' {fRelMovSetor},
  URelMovSetorDet in 'URelMovSetorDet.pas' {fRelMovSetorDet},
  uConfirmacao in 'uConfirmacao.pas' {fConfirmacao},
  UConsConfirmacao in 'UConsConfirmacao.pas' {fConsConfirmacao},
  UTipoMaterial in 'UTipoMaterial.pas' {fTipoMaterial},
  UFichaConsumoMat in 'UFichaConsumoMat.pas' {fFichaConsumoMat},
  UFichaConsumoMatItens in 'UFichaConsumoMatItens.pas' {fFichaConsumoMatItens},
  URelFichaConsumoMat in 'URelFichaConsumoMat.pas' {fRelFichaConsumoMat},
  UConsFichaConsumo in 'UConsFichaConsumo.pas' {fConsFichaConsumo},
  UPrevVendasVendModelo in 'UPrevVendasVendModelo.pas' {fPrevVendasVendModelo},
  UProdutoComb in 'UProdutoComb.pas' {fProdutoComb},
  UProdutoMat in 'UProdutoMat.pas' {fProdutoMat},
  URelPedidoBR2 in 'URelPedidoBR2.pas' {fRelPedidoBR2},
  UConsPedidoBR in 'UConsPedidoBR.pas' {fConsPedidoBR},
  UTalaoTrocaFabrica in 'UTalaoTrocaFabrica.pas' {fTalaoTrocaFabrica},
  UPrevBalancoEstUF in 'UPrevBalancoEstUF.pas' {fPrevBalancoEstUF},
  UPrevBalancoEstUF2 in 'UPrevBalancoEstUF2.pas' {fPrevBalancoEstUF2},
  UConsConsumoMat in 'UConsConsumoMat.pas' {fConsConsumoMat},
  URelConsumoMat in 'URelConsumoMat.pas' {fRelConsumoMat},
  UContasPagar2 in 'UContasPagar2.pas' {fContasPagar2},
  UContasPagarPagSel in 'UContasPagarPagSel.pas' {fContasPagarPagSel},
  URelCPagar3 in 'URelCPagar3.pas' {fRelCPagar3},
  UConfirmaProduto in 'UConfirmaProduto.pas' {fConfirmaProduto},
  URelTalao2 in 'URelTalao2.pas' {fRelTalao2},
  URelTalaoMI2 in 'URelTalaoMI2.pas' {fRelTalaoMI2},
  FixBDE4GbBug in '..\generico\Util\FixBDE4GbBug.pas',
  URelTalaoAuxiliar in 'URelTalaoAuxiliar.pas' {fRelTalaoAuxiliar},
  UTalaoAuxiliar in 'UTalaoAuxiliar.pas' {fTalaoAuxiliar},
  URelTalaoAuxiliarLote in 'URelTalaoAuxiliarLote.pas' {fRelTalaoAuxiliarLote},
  UPrevRelProgramacao in 'UPrevRelProgramacao.pas' {fPrevRelProgramacao},
  URelProgramacao in 'URelProgramacao.pas' {fRelProgramacao},
  UConsProgramacao in 'UConsProgramacao.pas' {fConsProgramacao},
  UProgramacaoOrdem in 'UProgramacaoOrdem.pas' {fProgramacaoOrdem},
  UCalculaDatas in 'UCalculaDatas.pas' {fCalculaDatas},
  UAlteraProgItem in 'UAlteraProgItem.pas' {fAlteraProgItem},
  UConsItemPed in 'UConsItemPed.pas' {fConsItemPed},
  UDMProg in 'UDMProg.pas' {DMProg: TDataModule},
  UConsTalaoAuxiliar in 'UConsTalaoAuxiliar.pas' {fConsTalaoAuxiliar},
  ULeitorTalaoAuxiliar in 'ULeitorTalaoAuxiliar.pas' {fLeitorTalaoAuxiliar},
  UConsProgramacaoItens in 'UConsProgramacaoItens.pas' {fConsProgramacaoItens},
  rsDataSetError in '..\rslib\rsDataSetError.pas',
  URelProgramacao2 in 'URelProgramacao2.pas' {fRelProgramacao2},
  UConsMaterialParaFicha in 'UConsMaterialParaFicha.pas' {fConsMaterialParaFicha},
  UConsMaterialFicha in 'UConsMaterialFicha.pas' {fConsMaterialFicha},
  UAcessoAltSenha in 'UAcessoAltSenha.pas' {fAcessoAltSenha},
  URelProducao in 'URelProducao.pas' {fRelProducao},
  uConsLoteProdPend in 'uConsLoteProdPend.pas' {fConsLoteProdPend},
  uNFe in '..\generico\faturamento\uNFe.pas' {fNFe},
  nfe_v110 in '..\generico\faturamento\nfe_v110.pas',
  uNFeComandos in '..\generico\faturamento\uNFeComandos.pas',
  URelDanfe in '..\generico\faturamento\URelDANFE.pas' {fRelDANFE},
  UDMNotaFiscal in 'UDMNotaFiscal.pas' {DMNotaFiscal: TDataModule},
  UGeracoes in '..\generico\faturamento\UGeracoes.pas',
  UNFeDados in 'UNFeDados.pas',
  UPais in '..\generico\manutencao\UPais.pas' {fPais},
  UNotaFiscalCancelada in '..\generico\faturamento\UNotaFiscalCancelada.pas' {fNotaFiscalCancelada},
  UNotaFiscalConfirma in '..\generico\faturamento\UNotaFiscalConfirma.pas' {fNotaFiscalConfirma},
  UOutrosServicosNota in '..\generico\faturamento\UOutrosServicosNota.pas' {fOutrosServicosNota},
  UNotaFiscalItensObsComplementar in 'UNotaFiscalItensObsComplementar.pas' {fNotaFiscalItensObsComplementar},
  UNotaFiscalImp in '..\generico\faturamento\UNotaFiscalImp.pas' {fNotaFiscalImp},
  UNotaFiscalOutrasDespesas in '..\generico\faturamento\UNotaFiscalOutrasDespesas.pas' {fNotaFiscalOutrasDespesas},
  UFilial in '..\generico\Manutencao\UFilial.pas' {fFilial},
  uRelPrevMetas in 'uRelPrevMetas.pas' {fRelPrevMetas},
  UVerificaContasRecPag in 'UVerificaContasRecPag.pas' {fVerificaContasRecPag},
  URelCalcMaterialLote in 'URelCalcMaterialLote.pas' {fRelCalcMaterialLote},
  UPrevCalcMaterialLote2 in 'UPrevCalcMaterialLote2.pas' {fPrevCalcMaterialLote2},
  UEscFornecedor in 'UEscFornecedor.pas' {fEscFornecedor},
  UConsCalcMaterialPed in 'UConsCalcMaterialPed.pas' {fConsCalcMaterialPed},
  UOrdemCompraLote in 'UOrdemCompraLote.pas' {fOrdemCompraLote},
  UComissaoVend in 'UComissaoVend.pas' {fComissaoVend},
  UClasFiscal in '..\generico\manutencao\UClasFiscal.pas' {fClasFiscal},
  UTransp in '..\generico\manutencao\UTransp.pas' {fTransp},
  UCidade in '..\generico\manutencao\UCidade.pas' {fCidade},
  UAutorizacao in '..\generico\manutencao\UAutorizacao.pas' {fAutorizacao},
  UAtividade in '..\generico\manutencao\UAtividade.pas' {fAtividade},
  UCondPgto in '..\generico\manutencao\UCondPgto.pas' {fCondPgto},
  UConsFornecAtiv in '..\generico\manutencao\UConsFornecAtiv.pas' {fConsFornecAtiv},
  UCopiaCli in '..\generico\manutencao\UCopiaCli.pas' {fCopiaCli},
  UCor in '..\generico\manutencao\UCor.pas' {fCor},
  UCSTIPI in '..\generico\manutencao\UCSTIPI.pas' {fCSTIPI},
  UEscImpressora in '..\generico\manutencao\UEscImpressora.pas' {fEscImpressora},
  UHistorico in '..\generico\manutencao\UHistorico.pas' {fHistorico},
  UImpressora in '..\generico\manutencao\UImpressora.pas' {fImpressora},
  UNatOperacao in '..\generico\manutencao\UNatOperacao.pas',
  UObsAux in '..\generico\manutencao\UObsAux.pas' {fObsAux},
  USitTributaria in '..\generico\manutencao\USitTributaria.pas' {fSitTributaria},
  USitTributariaSimples in '..\generico\manutencao\USitTributariaSimples.pas' {fSitTributariaSimples},
  UUf in '..\generico\manutencao\UUf.pas' {fUf},
  UIndexador in '..\generico\faturamento\UIndexador.pas' {fIndexador},
  UDMTabImposto in '..\generico\faturamento\UDMTabImposto.pas' {DMTabImposto: TDataModule},
  uCalculos in '..\generico\faturamento\uCalculos.pas',
  UDMNFe in '..\generico\faturamento\UDMNFe.pas' {DMNFe: TDataModule},
  UJuros in '..\generico\financeiro\UJuros.pas' {fJuros},
  UInfDescontoNota in '..\generico\faturamento\UInfDescontoNota.pas' {fInfDescontoNota},
  UNFeInutilizacao in '..\generico\faturamento\UNFeInutilizacao.pas' {fNFeInutilizacao},
  UNotaFiscalContingencia in '..\generico\faturamento\UNotaFiscalContingencia.pas' {fNotaFiscalContingencia},
  UNotaFiscalLacre in '..\generico\faturamento\UNotaFiscalLacre.pas' {fNotaFiscalLacre},
  UTabPis in '..\generico\faturamento\UTabPis.pas' {fTabPis},
  UTabCofins in '..\generico\faturamento\UTabCofins.pas' {fTabCofins},
  URegimeTrib in '..\generico\faturamento\URegimeTrib.pas' {fRegimeTrib},
  UNotaFiscalReboque in '..\generico\faturamento\UNotaFiscalReboque.pas' {fNotaFiscalReboque},
  UPercSimples in '..\generico\faturamento\UPercSimples.pas' {fPercSimples},
  UNotaFiscalRef in '..\generico\faturamento\UNotaFiscalRef.pas' {fNotaFiscalRef},
  UOrigemProd in '..\generico\faturamento\UOrigemProd.pas' {fOrigemProd},
  UNotaFiscalAliq in '..\generico\faturamento\UNotaFiscalAliq.pas' {fNotaFiscalAliq},
  UNotaFiscalOBS in '..\generico\faturamento\UNotaFiscalOBS.pas' {fNotaFiscalOBS},
  UVerificaGradeMateriais in 'UVerificaGradeMateriais.pas' {fVerificaGradeMateriais},
  URelVerificaGradeMat in 'URelVerificaGradeMat.pas' {fRelVerificaGradeMat},
  URelNatOper in '..\generico\manutencao\URelNatOper.pas' {fRelNatOper},
  UAgendaTelef in 'UAgendaTelef.pas' {fAgendaTelef},
  UOutros in 'UOutros.pas' {fOutros},
  URelAgendaTelef in 'URelAgendaTelef.pas' {fRelAgendaTelef},
  UDM1 in 'UDM1.pas' {DM1: TDataModule},
  UDM2 in 'UDM2.pas' {DM2: TDataModule},
  URelNavalhaLocal in 'URelNavalhaLocal.pas' {fRelNavalhaLocal},
  UDMCia in 'UDMCia.pas' {DMCia: TDataModule},
  UCia in 'UCia.pas' {fCia},
  URelCiaCad in 'URelCiaCad.pas' {fRelCiaCad},
  UCopiaCliFornec in 'UCopiaCliFornec.pas' {fCopiaCliFornec},
  UDMMaterialFornecedor in '..\generico\Compras\UDMMaterialFornecedor.pas' {DMMaterialFornecedor: TDataModule},
  UMaterialFornecedor in '..\generico\Compras\UMaterialFornecedor.pas' {fMaterialFornecedor},
  UPrevBalancoEstUF3 in 'UPrevBalancoEstUF3.pas' {fPrevBalancoEstUF3},
  uEmailNFeC in 'uEmailNFeC.pas' {fEmailNFeC},
  uEmailNFeR in 'uEmailNFeR.pas' {fEmailNFeR},
  DmdDatabase in 'FB\DmdDatabase.pas' {dmDatabase: TDataModule},
  LogProvider in '..\logs\src\LogProvider.pas',
  LogTypes in '..\logs\src\LogTypes.pas',
  UDMFichaConstrucao in 'FB\UDMFichaConstrucao.pas' {DMFichaConstrucao: TDataModule},
  UFichaConstrucaoC in 'FB\UFichaConstrucaoC.pas' {fFichaConstrucaoC},
  UFichaConstrucao in 'FB\UFichaConstrucao.pas' {fFichaConstrucao},
  arTypes in '..\rslib\arTypes.pas',
  UDMPosicao_Ficha in 'FB\UDMPosicao_Ficha.pas' {DMPosicao_Ficha: TDataModule},
  UFichaConstrucao_Pos in 'FB\UFichaConstrucao_Pos.pas' {fFichaConstrucao_Pos},
  UFichaConstrucao_Mat in 'FB\UFichaConstrucao_Mat.pas' {fFichaConstrucao_Mat},
  uIntegracao in 'FB\uIntegracao.pas',
  UPosicaoFichaC in 'FB\UPosicaoFichaC.pas' {fPosicaoFichaC},
  UPosicaoFicha in 'FB\UPosicaoFicha.pas' {fPosicaoFicha},
  URelFichaConstrucao in 'URelFichaConstrucao.pas' {fRelFichaConstrucao},
  UConsLoteOpcao in 'UConsLoteOpcao.pas' {fConsLoteOpcao},
  UDMNFeFB in '..\generico\faturamento\UDMNFeFB.pas' {DMNFeFB: TDataModule},
  UNotaFiscalCCe in '..\generico\faturamento\UNotaFiscalCCe.pas' {fNotaFiscalCCe},
  UNotaFiscalCCeDet in '..\generico\faturamento\UNotaFiscalCCeDet.pas' {fNotaFiscalCCeDet},
  URelCCe in '..\generico\faturamento\URelCCe.pas' {fRelCCe},
  UNFeEmailC in '..\generico\faturamento\UNFeEmailC.pas' {fNFeEmailC},
  UNFeEmail in '..\generico\faturamento\UNFeEmail.pas' {fNFeEmail},
  dmdCadCor in 'FB\dmdCadCor.pas' {dmCadCor: TDataModule},
  UGerarEFD in 'UGerarEFD.pas' {fGerarEFD},
  dmdCadTalaoGrade in 'FB\dmdCadTalaoGrade.pas' {dmCadTalaoGrade: TDataModule},
  UGeraFB in 'UGeraFB.pas' {fGeraFB},
  UConsClientes in 'UConsClientes.pas' {fConsClientes},
  uRelClientes2 in 'URelClientes2.pas' {fRelClientes2},
  UPrevRelDuplicatas in 'UPrevRelDuplicatas.pas' {fPrevRelDuplicatas},
  URelDuplicata in 'URelDuplicata.pas' {fRelDuplicata},
  uProdutosVendidos in 'uProdutosVendidos.pas' {fProdutosVendidos},
  uProdutosVendidosR in 'uProdutosVendidosR.pas' {fProdutosVendidosR},
  dmdCadTalaoMov in 'fb\dmdCadTalaoMov.pas' {dmCadTalaoMov: TDataModule},
  dmdCadTalao in 'fb\dmdCadTalao.pas' {dmCadTalao: TDataModule},
  dmdCadLote in 'fb\dmdCadLote.pas' {dmCadLote: TDataModule},
  UConsMaterialPeriodo in 'UConsMaterialPeriodo.pas' {fConsMaterialPeriodo},
  URelMaterialPeriodo in 'URelMaterialPeriodo.pas' {fRelMaterialPeriodo},
  UEtiqNota in 'UEtiqNota.pas' {fEtiqNota},
  URelEtiqNota in 'URelEtiqNota.pas' {fRelEtiqNota},
  USel_Produto in 'USel_Produto.pas' {fSel_Produto},
  uUtilPadrao in 'uUtilPadrao.pas',
  uNotaFiscalAjustarIcms in '..\generico\faturamento\uNotaFiscalAjustarIcms.pas' {fNotaFiscalAjustarIcms},
  UConvFotoProd in 'UConvFotoProd.pas' {fConvFotoProd},
  UPrevPre2 in 'UPrevPre2.pas' {fPrevPre2},
  URelPre2 in 'URelPre2.pas' {fRelPre2},
  dmdCadProduto in 'fb\dmdCadProduto.pas' {dmCadProduto: TDataModule},
  UDMArmazenamento_Ref in 'fb\UDMArmazenamento_Ref.pas' {DMArmazenamento_Ref: TDataModule},
  rsDBUtils in '..\rslib\nova\rsDBUtils.pas',
  UArmazenamento_RefC in 'fb\UArmazenamento_RefC.pas' {fArmazenamento_RefC},
  UArmazenamento_Ref in 'fb\UArmazenamento_Ref.pas' {fArmazenamento_Ref},
  UDMNavalha_Local in 'fb\UDMNavalha_Local.pas' {DMNavalha_Local: TDataModule},
  UNavalha_LocalC in 'fb\UNavalha_LocalC.pas' {fNavalha_LocalC},
  UNavalha_Local in 'fb\UNavalha_Local.pas' {fNavalha_Local},
  UDMConstrucao in 'UDMConstrucao.pas' {DMConstrucao: TDataModule},
  UConsProduto in 'UConsProduto.pas' {fConsProduto},
  USel_Cliente in 'USel_Cliente.pas' {fSel_Cliente},
  dmdCadCliente in 'fb\dmdCadCliente.pas' {dmCadCliente: TDataModule},
  dmdCadMaterial in 'fb\dmdCadMaterial.pas' {dmCadMaterial: TDataModule},
  dmdCadCReceber in 'fb\dmdCadCReceber.pas' {dmCadCReceber: TDataModule},
  UGeraFB_Exc in 'UGeraFB_Exc.pas' {fGeraFB_Exc},
  dmdCadTalaoAuxiliar in 'fb\dmdCadTalaoAuxiliar.pas' {dmTalaoAuxiliar: TDataModule},
  UGeraFBMI_Exc in 'UGeraFBMI_Exc.pas' {fGeraFBMI_Exc},
  uNFeConsts in '..\NFe 3.10\NFESrv\uNFeConsts.pas',
  DmdDatabase_NFeBD in '..\generico\NFe\DmdDatabase_NFeBD.pas' {dmDatabase_NFeBD: TDataModule},
  dmdNFeConfig in '..\generico\NFe\dmdNFeConfig.pas' {DMNFeConfig: TDataModule},
  enviNFe_v310 in '..\generico\NFe\enviNFe_v310.pas',
  UDMConsNotaEletronica in '..\generico\NFe\UDMConsNotaEletronica.pas' {DMConsNotaEletronica: TDataModule},
  uXMLNFe3_10 in '..\generico\NFe\uXMLNFe3_10.pas',
  uUtil in 'uUtil.pas',
  uUtil_NFe in '..\generico\faturamento\uUtil_NFe.pas',
  URelTalaoMI3 in 'URelTalaoMI3.pas' {fRelTalaoMI3},
  UConsMaterial in 'UConsMaterial.pas' {fConsMaterial},
  UDMTabEnqIPI in '..\generico\faturamento\UDMTabEnqIPI.pas' {DMTabEnqIPI: TDataModule},
  UTabEnqIPIC in '..\generico\faturamento\UTabEnqIPIC.pas' {fTabEnqIPIC},
  UTabEnqIPI in '..\generico\faturamento\UTabEnqIPI.pas' {fTabEnqIPI},
  USel_EnqIPI in '..\generico\faturamento\USel_EnqIPI.pas' {fSel_EnqIPI},
  UDMNotaFiscalFB in 'fb\UDMNotaFiscalFB.pas' {DMNotaFiscalFB: TDataModule},
  UCadNotaFiscal_Itens_DrawBack in 'fb\UCadNotaFiscal_Itens_DrawBack.pas' {frmCadNotaFiscal_Itens_DrawBack},
  enviNFe_v400 in '..\generico\NFe\4.00\enviNFe_v400.pas',
  uXMLNFe4_00 in '..\generico\NFe\4.00\uXMLNFe4_00.pas';

{$R *.RES}

begin
  Application.Initialize;
  Session.AddPassword('46w3zq');
  Application.Title := 'Lotus';
  Application.CreateForm(TdmDatabase, dmDatabase);
  Application.CreateForm(TDM1, DM1);
  Application.CreateForm(TDM2, DM2);
  Application.CreateForm(TfMenuP, fMenuP);
  Application.Run;
end.
